permalink:           pretty

# Setup
title:               오성국 블로그
tagline:             '이것저것 끄적끄적'
description:         '1년차 개발자, Python Django Flask JavaScript Nodejs React React-Native Android 등을 사용해 보았습니다.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Oh Sung Kook
  url:               https://github.com/osunguk
  email:             osunguk@gmail.com

# Custom vars
version:             1.1.0

plugins: [jekyll-paginate]